
title: Darwin Free University
timezone: Australia/Darwin
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A free grassroots autonomous space run twice a month at Darwin Community Arts
  in Coconut Grove dedicated to the radical redistributing of education and learning.
facebook:
  publisher: https://www.facebook.com/DarwinFreeUniversity/
logo: "/assets/img/dfu-circle.svg"
email: darwinfreeuniversity@gmail.com
url: https://darwinfree.university
github_username: darwinfreeuniversity
instagram_username: darwinfreeuniversity
repository: darwinfreeuniversity/darwinfreeuniversity.github.io
markdown: kramdown
kramdown:
  parse_block_html: true
theme: jekyll-theme-minimal
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
sass:
  sass_dir: assets/css
simple-form: https://simple-form.com/darwinfreeuniversity@gmail.com
dfu-facebook: https://www.facebook.com/DarwinFreeUniversity
dfu-homepage: https://darwinfree.university

